services:
  multiarch-test:
    image: prashantbhu/multi-arch-test:latest
    container_name: multiarch_test_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
